# Generated by Django 4.2.30 on 2026-05-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dev_eui",
                    models.CharField(db_index=True, max_length=16, unique=True),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("passing", models.BooleanField(default=True)),
                ("fcnt_latest", models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name="Payload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=512)),
                ("fcnt", models.IntegerField()),
                ("rx_info", models.JSONField(blank=True, default=list)),
                ("tx_info", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payloads",
                        to="approot.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("device", "fcnt")},
            },
        ),
    ]
